### ISSUE TITLE
iPhone?

### ISSUE THREAD

**Issue by gagagu** [wilsonwong13/Prism-Leap-Watson#3]
Hi,
which phone are you using and how do you connect it to the leap motion device?
I thinking about to use an leap motion device with my iphone (and mira prism) but the iphone is not able to connect to the leap motion device directly.

**Comment by wilsonwong13** [comment]
Hey, 
I'm currently using an iphone 6s, and I'm using my computer to connect to the leap motion device. I couldn't find a way to connect the leap motion with the iphone. If you find a way please dm me.
